# Update subscription links
name: Daily Update

on:
  # Runs every 8 hours
  schedule:
    - cron: '0 */8 * * *'

  # Manual updates
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - name: Update Links & Combine Configs
        # Condition to prevent unintended automatic workflow
        # Change or comment out this line for automatic workflow on forks
        if: github.repository == 'williamstar007/clashx-v2ray-topfreeproxy'
        run: |          
          echo "$(date '+%Y-%m-%d %H:%M:%S')" > combine/.timestamp
          python .github/workflows/update.py
          python combine/combine.py
          
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "updates"
          git push
          
